### PR TITLE
Added missing prereq LWP::UserAgent as suggested by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @nics 

Please review the PR.
https://cpants.cpanauthors.org/release/NICS/Catmandu-Solr-0.0303

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by nicolasfranck** [comment]
I guess you meant `LWP::UserAgent` instead of `LPW::UserAgent`?

That is already a dependency of `WebService::Solr`.

**Comment by nics** [comment]
The point is not using implicit dependencies. What if Webservice::Solr
changes it's http client?

**Comment by nicolasfranck** [comment]
@nics : I know, but I guess not all user agents have the same methods, so there will always dependencies on certain types of agents. Not?

**Comment by nics** [comment]
Please just add the dependencies, this is a great service by cpants.

**Comment by manwar** [comment]
Opps, sorry about the typo.
I have fixed the typo and rebase it.
Please have a look.

**Pull request merged**
